push

diff --git a/bin/index b/bin/index
--- a/bin/index
+++ b/bin/index
@@ -1,6 +1,6 @@
-#!/bin/sh
+#!/bin/bash
 
-# set -Eeuo pipefail
+set -Eeuo pipefail
 
 
 start() {
@@ -21,6 +21,22 @@ stop() {
     pkill -f "flask --app index run --host 0.0.0.0 --port 9002" || true
 }
 
+status() {
+    set +o pipefail
+    NPROCS=$(pgrep -f "flask --app index run --host 0.0.0.0 --port 900[0-2]" | wc -l)
+    set -o pipefail
+    if [ "$NPROCS" -eq 3 ]; then
+    echo "index server running"
+    exit
+    elif [ "$NPROCS" -eq 0 ]; then
+    echo "index server stopped"
+    exit 1
+    else
+    echo "index server error: found ${NPROCS} processes, expected 3"
+    exit 2
+    fi
+}
+
 case $1 in
     "start")
         start
@@ -31,6 +47,9 @@ case $1 in
     "restart")
         stop
         start
+        ;;
+    "status")
+        status
         ;;
     *)
         exit 1
